services:
  - type: web
    name: omegax-bot
    env: python
    plan: starter
    buildCommand: pip install Flask==2.3.3 requests==2.31.0
    startCommand: python main.py
    envVars:
      - key: WEB_UI_PASSWORD
        value: omegax2024
      - key: USE_REALISTIC_PAPER
        value: true
    healthCheckPath: /ping