services:
  - type: web
    name: omegax-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: USE_REALISTIC_PAPER
        value: "true"
      - key: PORT
        value: "10000"
    healthCheckPath: /