services:
  - type: web
    name: omegax-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WEB_UI_PASSWORD
        value: omegax2024
      - key: USE_REALISTIC_PAPER
        value: true
      - key: INITIAL_BALANCE
        value: "1000"
      - key: LEVERAGE
        value: "10"
      - key: MAX_POSITIONS
        value: "12"
    healthCheckPath: /ping
    autoDeploy: true