services:
  - type: web
    name: omegax-trading-bot
    env: python
    runtime: python-3.10
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    plan: starter
    
    envVars:
      - key: PORT
        value: 8080
      - key: WEB_UI_PASSWORD
        value: omegax2024!
      - key: BINANCE_API_KEY
        value: ""
      - key: TELEGRAM_TOKEN
        value: ""
      - key: TELEGRAM_CHAT_ID
        value: ""
      - key: USE_REALISTIC_PAPER
        value: "true"
    
    healthCheckPath: /ping
    
    disk:
      name: omegax-db
      mountPath: /opt/render/project/src
      sizeGB: 1
    
    autoDeploy: true